INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (1, 1, 'A. 小于1年', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (2, 1, 'B. 1-2年', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (3, 1, 'C. 大于2年', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (4, 2, 'A. 从不', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (5, 2, 'B. 1-2次/周', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (6, 2, 'C. ≥3次/周', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (7, 3, 'A. 有', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (8, 3, 'B. 没有', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (9, 4, 'A. 有', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (10, 4, 'B. 没有', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (11, 5, 'A. 有', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (12, 5, 'B. 没有', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (13, 6, 'A. 无疼痛', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (14, 6, 'B. 有疼痛', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (15, 7, 'A. 轻度疼痛', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (16, 7, 'B. 中度疼痛 ', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (17, 7, 'C. 重度疼痛', 6, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (18, 8, 'A. 不影响睡眠', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (19, 8, 'B. 轻度影响睡眠', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (20, 8, 'C. 中度影响睡眠', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (21, 8, 'D. 严重影响睡眠 ', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (22, 9, 'A. 基本没有任何影响 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (23, 9, 'B. 轻度影响', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (24, 9, 'C. 中度影响', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (25, 9, 'D. 严重影响（无法进行训练）', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (26, 10, 'A. 从未出现 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (27, 10, 'B. 偶有出现 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (28, 10, 'C. 经常出现', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (29, 11, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (30, 11, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (31, 11, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (32, 11, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (33, 11, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (34, 12, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (35, 12, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (36, 12, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (37, 12, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (38, 12, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (39, 13, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (40, 13, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (41, 13, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (42, 13, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (43, 13, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (44, 14, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (45, 14, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (46, 14, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (47, 14, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (48, 14, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (49, 15, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (50, 15, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (51, 15, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (52, 15, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (53, 15, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (54, 16, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (55, 16, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (56, 16, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (57, 16, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (58, 16, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (59, 17, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (60, 17, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (61, 17, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (62, 17, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (63, 17, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (64, 18, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (65, 18, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (66, 18, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (67, 18, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (68, 18, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (69, 19, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (70, 19, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (71, 19, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (72, 19, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (73, 19, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (74, 20, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (75, 20, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (76, 20, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (77, 20, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (78, 20, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (79, 21, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (80, 21, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (81, 21, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (82, 21, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (83, 21, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (84, 22, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (85, 22, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (86, 22, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (87, 22, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (88, 22, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (89, 23, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (90, 23, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (91, 23, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (92, 23, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (93, 23, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (94, 24, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (95, 24, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (96, 24, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (97, 24, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (98, 24, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (99, 25, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (100, 25, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (101, 25, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (102, 25, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (103, 25, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (104, 26, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (105, 26, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (106, 26, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (107, 26, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (108, 26, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (109, 27, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (110, 27, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (111, 27, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (112, 27, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (113, 27, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (114, 28, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (115, 28, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (116, 28, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (117, 28, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (118, 28, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (119, 29, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (120, 29, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (121, 29, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (122, 29, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (123, 29, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (124, 30, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (125, 30, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (126, 30, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (127, 30, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (128, 30, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (129, 31, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (130, 31, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (131, 31, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (132, 31, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (133, 31, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (134, 32, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (135, 32, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (136, 32, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (137, 32, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (138, 32, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (139, 33, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (140, 33, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (141, 33, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (142, 33, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (143, 33, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (144, 34, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (145, 34, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (146, 34, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (147, 34, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (148, 34, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (149, 35, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (150, 35, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (151, 35, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (152, 35, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (153, 35, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (154, 36, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (155, 36, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (156, 36, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (157, 36, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (158, 36, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (159, 37, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (160, 37, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (161, 37, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (162, 37, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (163, 37, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (164, 38, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (165, 38, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (166, 38, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (167, 38, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (168, 38, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (169, 39, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (170, 39, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (171, 39, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (172, 39, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (173, 39, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (174, 40, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (175, 40, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (176, 40, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (177, 40, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (178, 40, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (179, 41, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (180, 41, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (181, 41, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (182, 41, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (183, 41, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (184, 42, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (185, 42, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (186, 42, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (187, 42, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (188, 42, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (189, 43, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (190, 43, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (191, 43, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (192, 43, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (193, 43, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (194, 44, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (195, 44, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (196, 44, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (197, 44, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (198, 44, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (199, 45, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (200, 45, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (201, 45, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (202, 45, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (203, 45, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (204, 46, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (205, 46, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (206, 46, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (207, 46, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (208, 46, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (209, 47, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (210, 47, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (211, 47, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (212, 47, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (213, 47, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (214, 48, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (215, 48, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (216, 48, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (217, 48, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (218, 48, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (219, 49, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (220, 49, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (221, 49, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (222, 49, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (223, 49, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (224, 50, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (225, 50, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (226, 50, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (227, 50, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (228, 50, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (229, 51, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (230, 51, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (231, 51, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (232, 51, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (233, 51, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (234, 52, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (235, 52, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (236, 52, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (237, 52, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (238, 52, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (239, 53, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (240, 53, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (241, 53, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (242, 53, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (243, 53, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (244, 54, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (245, 54, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (246, 54, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (247, 54, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (248, 54, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (249, 55, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (250, 55, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (251, 55, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (252, 55, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (253, 55, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (254, 56, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (255, 56, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (256, 56, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (257, 56, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (258, 56, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (259, 57, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (260, 57, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (261, 57, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (262, 57, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (263, 57, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (264, 58, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (265, 58, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (266, 58, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (267, 58, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (268, 58, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (269, 59, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (270, 59, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (271, 59, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (272, 59, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (273, 59, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (274, 60, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (275, 60, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (276, 60, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (277, 60, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (278, 60, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (279, 61, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (280, 61, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (281, 61, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (282, 61, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (283, 61, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (284, 62, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (285, 62, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (286, 62, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (287, 62, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (288, 62, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (289, 63, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (290, 63, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (291, 63, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (292, 63, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (293, 63, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (294, 64, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (295, 64, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (296, 64, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (297, 64, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (298, 64, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (299, 65, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (300, 65, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (301, 65, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (302, 65, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (303, 65, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (304, 66, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (305, 66, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (306, 66, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (307, 66, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (308, 66, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (309, 67, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (310, 67, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (311, 67, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (312, 67, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (313, 67, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (314, 68, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (315, 68, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (316, 68, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (317, 68, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (318, 68, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (319, 69, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (320, 69, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (321, 69, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (322, 69, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (323, 69, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (324, 70, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (325, 70, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (326, 70, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (327, 70, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (328, 70, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (329, 71, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (330, 71, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (331, 71, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (332, 71, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (333, 71, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (334, 72, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (335, 72, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (336, 72, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (337, 72, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (338, 72, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (339, 73, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (340, 73, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (341, 73, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (342, 73, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (343, 73, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (344, 74, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (345, 74, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (346, 74, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (347, 74, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (348, 74, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (349, 75, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (350, 75, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (351, 75, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (352, 75, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (353, 75, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (354, 76, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (355, 76, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (356, 76, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (357, 76, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (358, 76, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (359, 77, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (360, 77, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (361, 77, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (362, 77, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (363, 77, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (364, 78, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (365, 78, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (366, 78, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (367, 78, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (368, 78, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (369, 79, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (370, 79, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (371, 79, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (372, 79, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (373, 79, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (374, 80, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (375, 80, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (376, 80, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (377, 80, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (378, 80, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (379, 81, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (380, 81, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (381, 81, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (382, 81, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (383, 81, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (384, 82, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (385, 82, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (386, 82, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (387, 82, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (388, 82, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (389, 83, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (390, 83, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (391, 83, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (392, 83, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (393, 83, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (394, 84, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (395, 84, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (396, 84, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (397, 84, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (398, 84, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (399, 85, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (400, 85, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (401, 85, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (402, 85, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (403, 85, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (404, 86, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (405, 86, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (406, 86, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (407, 86, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (408, 86, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (409, 87, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (410, 87, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (411, 87, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (412, 87, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (413, 87, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (414, 88, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (415, 88, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (416, 88, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (417, 88, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (418, 88, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (419, 89, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (420, 89, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (421, 89, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (422, 89, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (423, 89, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (424, 90, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (425, 90, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (426, 90, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (427, 90, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (428, 90, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (429, 91, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (430, 91, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (431, 91, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (432, 91, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (433, 91, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (434, 92, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (435, 92, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (436, 92, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (437, 92, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (438, 92, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (439, 93, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (440, 93, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (441, 93, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (442, 93, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (443, 93, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (444, 94, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (445, 94, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (446, 94, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (447, 94, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (448, 94, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (449, 95, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (450, 95, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (451, 95, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (452, 95, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (453, 95, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (454, 96, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (455, 96, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (456, 96, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (457, 96, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (458, 96, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (459, 97, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (460, 97, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (461, 97, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (462, 97, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (463, 97, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (464, 98, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (465, 98, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (466, 98, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (467, 98, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (468, 98, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (469, 99, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (470, 99, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (471, 99, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (472, 99, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (473, 99, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (474, 100, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (475, 100, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (476, 100, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (477, 100, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (478, 100, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (479, 101, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (480, 101, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (481, 101, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (482, 101, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (483, 101, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (484, 102, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (485, 102, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (486, 102, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (487, 102, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (488, 102, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (489, 103, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (490, 103, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (491, 103, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (492, 103, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (493, 103, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (494, 104, 'A. 无法完成或极其困难', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (495, 104, 'B. 可以完成，但很困难 ', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (496, 104, 'C. 可以完成，中等难度', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (497, 104, 'D. 可以完成，轻微难度', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (498, 104, 'E. 轻松完成，没有难度 ', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (499, 105, 'A. 下降', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (500, 105, 'B. 不变', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (501, 105, 'C. 提高', -1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (502, 105, 'D. 不确定', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (503, 106, 'A. 是', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (504, 106, 'B. 否', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (505, 107, 'A. <24小时', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (506, 107, 'B. 24-72小时', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (507, 107, 'C. >72小时', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (508, 108, 'A. 是', 3, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (509, 108, 'B. 否', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (510, 109, 'A. 严重影响', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (511, 109, 'B. 中度影响', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (512, 109, 'C. 轻微影响', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (513, 109, 'D.无影响', 0, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (514, 110, 'A. 严重影响', 4, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (515, 110, 'B. 中度影响', 2, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (516, 110, 'C. 轻微影响', 1, 0, 0, 0);
INSERT INTO `omo_stat_question_options`(`id`, `question_id`, `option_name`, `option_score`, `deleted`, `updated`, `created`) VALUES (517, 110, 'D.无影响', 0, 0, 0, 0);
